In [1]:
import numpy as np
import seaborn as sns

In [2]:
arr = np.array([2,3,4,6,7,8,9,12,13,16,17,23,25,27,34,37,201])
arr

array([  2,   3,   4,   6,   7,   8,   9,  12,  13,  16,  17,  23,  25,
        27,  34,  37, 201])

In [ ]:
Q1 = np.percentile(arr,25)
Q3 = np.percentile(arr,75)
print(f'Q1 {Q1}')
print(f'Q3 {Q3}')

Q1 7.0 and Q3 25.0


In [10]:
IQR = Q3-Q1
IQR

np.float64(18.0)

### Get Upper fence and Lower fence 

In [12]:
UF = Q3 + 1.5 * IQR
UF

np.float64(52.0)

In [15]:
LF = Q1 - (1.5 * IQR)
LF

np.float64(-20.0)

### Remove Outliers 

In [17]:
l = []

for i in arr:
    if (i >=LF and i <= UF):
        l.append(i)

In [20]:
arr2 = np.array(l)

In [22]:
print(arr)
print(arr2)

[  2   3   4   6   7   8   9  12  13  16  17  23  25  27  34  37 201]
[ 2  3  4  6  7  8  9 12 13 16 17 23 25 27 34 37]
